### ISSUE TITLE
4.11.0-beta1 PHP 8.1 - Cannot register

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-webauthn-authenticator#110]
Tested via adding additional method in myprofile

I got 'Key verified"

However clicking the "Complete registration" green button did nothing in Firefox

Console:

https://<mysite>/admin/mfa/register/web-authn?SecurityID=<hash>

Returned a 500

`error-log.ERROR: Uncaught Exception TypeError: "Webauthn\PublicKeyCredentialCreationOptions::createFromArray(): Argument #1 ($json) must be of type array, Webauthn\PublicKeyCredentialCreationOptions given, called in /sites/<mysite>/releases/20220511213243/vendor/silverstripe/webauthn-authenticator/src/RegisterHandler.php on line 251" at /sites/<mysite>/releases/20220511213243/vendor/web-auth/webauthn-lib/src/PublicKeyCredentialCreationOptions.php line 194 {"exception":"[object] (TypeError(code: 0): Webauthn\\PublicKeyCredentialCreationOptions::createFromArray(): Argument #1 ($json) must be of type array, Webauthn\\PublicKeyCredentialCreationOptions given, called in /sites/<mysite>/releases/20220511213243/vendor/silverstripe/webauthn-authenticator/src/RegisterHandler.php on line 251 at /sites/<mysite>/releases/20220511213243/vendor/web-auth/webauthn-lib/src/PublicKeyCredentialCreationOptions.php:194)"} []`

Update: surprisingly, despite the issue coming from mfa, totp seems to be be unaffected, only webauthn had issues

### PRs
- https://github.com/silverstripe/silverstripe-mfa/pull/455
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/112

**Comment by emteknetnz** [comment]
Issue is that the new __serialize/__unserialize implementations in silverstripe/mfa, while they are "correct" in that they keep the php objects like PublicKeyCredentialCreationOptions intact instead of just turning them into json, which becomes as assoc array, they aren't compatible with webauthn

We'll also need to double check that totp actually works correct since the issue is in mfa

Debugging at the top of silverstripe/webauthn-authenticator RegisterHandler::register()

mfa 4.6 (broken)
![mfa-4 6-webauthn](https://user-images.githubusercontent.com/4809037/167988364-288e91d1-f1d8-48a1-b850-c3e546824885.png)

mfa 4.5 (works)
![mfa-4 5-webauthn](https://user-images.githubusercontent.com/4809037/167988377-01132ce8-7400-434a-ab21-1a23561d0237.png)

**Comment by maxime-rainville** [comment]
All done!
