### ISSUE TITLE
Upgrade to web-auth/webauthn-lib ^4 for CMS 5

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-webauthn-authenticator#118]
Update web-auth/webauthn-lib ^3 to web-auth/webauthn-lib ^4 in order to order to get a symfony ^6 compatibility - web-auth/webauthn-lib ^3 requires a max of symfony/process ^5

https://github.com/web-auth/webauthn-lib/blob/v4.0/composer.json requires symfony/uid ^6 and php 8.1, so this change should only target CMS5 only and should be done on a new major

**Comment by maxime-rainville** [comment]
Folded back into https://github.com/silverstripeltd/product-issues/issues/582
