### ISSUE TITLE
CMS 5 - yubikey registration fails

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-webauthn-authenticator#124]
Follow on from https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/122

When I register for webauthn
And I press the yubikey
Then I see I Key Verified
When I click the "Complete registration" button
Then I see this

![image](https://user-images.githubusercontent.com/4809037/213031528-f105435a-e238-42b3-9de8-7a0ecac66bfc.png)

Exception comes from vendor/paragonie/contant_time_encoding/src/Base32.php

Possibly relevant - https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/122#issuecomment-1386194783

Related https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/127

## Acceptance criteria
- [ ] The thing works

## PRs
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/128

## Note
- Make an initial assessment about how complicated the fix will be. If it turns out to be a nightmare, call it out.
- We won't block the CMS5 beta for this, but it needs to be called out as a known issue.

**Comment by sabina-talipova** [comment]
There is an raised issue about this Error in web-auth/webauthn-framework
- https://github.com/web-auth/webauthn-framework/issues/285

One another solution here to downgrade `web-auth/webauthn-lib` version :
- https://github.com/asbiin/laravel-webauthn/issues/408#issuecomment-1378886130

**Comment by emteknetnz** [comment]
@sabina-talipova That looks promising, makes sense to try to manually remove the padding similar to the laravel example at first, and failing that downgrade to `~4.0.5` - we're currently on `^4.4` - https://github.com/silverstripe/silverstripe-webauthn-authenticator/blob/5/composer.json#L15, though that's less than ideal

**Comment by emteknetnz** [comment]
Note the latest version of web-auth/webauthn-lib gives a different response - the error is now "Registration failed: Unable to load the data" - this is because of this line https://github.com/web-auth/webauthn-lib/compare/4.4.3...4.5.1#diff-d6efd31abc9f65b2a796aeab582924a819658d2e628e12e5d018c886880d7471R122 - reverting it shows the "padding" message again.

**Comment by emteknetnz** [comment]
Have confirmed locally that using web-auth/webauthn-lib ~4.0.0 does resolve the issue

**Comment by maxime-rainville** [comment]
It all works fine.
