### ISSUE TITLE
Ability to define unsupported browsers

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#13]
Although the list grows, there are browsers that do not support the WebAuthn API, as a result, we want to highlight this to users who may use one of these browsers.

**ACs**
- A user trying to use this method in the MFA flow is given information as to why it won't work with their browser, and is blocked from using it
- This module has the ability to define unsupported browsers, configurable by a developer (or use something from WebAuthn?)
- API can be used by `silverstripe/mfa` to block the user from choosing to register or authentication with this method as part of the MFA flow

**Notes**
- Previous work has already been done on styling this message. So use what's available as part of completing this issue.
- We have a separate issue for improving the accessibility of the existing designs, here: #77

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-mfa/pull/190
- [ ] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/22

**Comment by brynwhyman** [comment]
I'd assume styling work would be complete as part of this work

**Comment by brynwhyman** [comment]
Closed for https://github.com/silverstripe/silverstripe-mfa/issues/81

**Comment by robbieaverill** [comment]
I think we can use any of these interfaces existence to check if webauthn is supported: https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#Interfaces

e.g. `typeof AuthenticatorResponse === 'undefined' { unsupported }`

**Comment by robbieaverill** [comment]
Hmmm, tricky - the MFA module is the part where it handles the "unavailable" logic. We may need the WebAuthn module to register something with Injector that defines whether it's available or not.

**Comment by newleeland** [comment]
### Potential design
Lives in the MFA Login flow

Select **Login with 2FA (existing users):** 
Select **If default method is unavailable**
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c68f96ffb26bb0018525d1a

Just FYI @brynwhyman 
Could we change the title to "Ability to define unavailable methods" as this message appear not just when the browser is unsupported and other scenarios.
@robbieaverill this solution uses the same template layout as the "MFA setup successful" layout

**Comment by robbieaverill** [comment]
@newleeland are you talking about my question in Slack about how we render automatically selected methods when they're unavailable?

FYI you design link doesn't work

**Comment by newleeland** [comment]
> @newleeland are you talking about my question in Slack about how we render automatically selected methods when they're unavailable?

Yes. just as reference everyone else. The **Potential design** address what people will see in the scenario where someone has setup a security key as their default MFA, however is trying to login to the CMS with an unsupported browser.

**Comment by robbieaverill** [comment]
PRs posted to the description
