### ISSUE TITLE
Finalise WebAuthn Registration / Verify UIs

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#14]
**Background**
Through some initial tests with this method it appears at some point we need to initiate the browser to take over the UI of authenticating with a security key.

The current flow doesn't seem intuitive. Without sufficient introduction messaging a user new to Yubikeys could be confused with the process.

**ACs**
- When registering or authenticating a Yubikey, the user understands what they need to do.
- At some point in the flow, the user has the ability to access the 'How to use security keys' link.
- During the flow, there's helpful troubleshooting information. I.e "...If it doesn't register, remove and re-insert you key.".
- The user doesn't get stuck if they're unavailable to authenticate, i.e there's the ability to 'try again', there's failure messages so the user knows what to do next.
- This should work in the CMS modal too.

Designs
- Latest designs are in the [comments below](https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/14#issuecomment-500678588)

Notes
- It seems Safari has no specific browser handling - this should be considered as part of any consideration

**Comment by brynwhyman** [comment]
Hey @newleeland this is the issue I've put together to refine the UX for registering or authenticating with a Yubikey.

I've tried to make the ACs not cover specific UI implementations but I'm keen on your feedback if you think there's other points we could include.

**Comment by brynwhyman** [comment]
Some considerations:
 - For registering you'll probably want a button (and more information) before prompting the browser
- For authenticating, you may just want a slight delay then an automatic prompt
- We can set timeouts, and functions to re-quest the prompt if it does time out

**Comment by brynwhyman** [comment]
We're delaying grooming of this issue until the designs are created.

**Comment by brynwhyman** [comment]
We understand that a new Safari beta will allow WebAuthn, but potentially without a browser dialog. We may need to keep a general approach in mind for this, or decide to come back to a Safari-specific implementation later.

**Comment by newleeland** [comment]
Ok I'll be extending our existing U2F design to accommodate WebAuthn. I'll be considering the following:

From the meeting we decided to:
- Direct user to register screen (with "register" button) so that user can view content introducing security keys
- Once key is registered, automatically direct user to recovery codes
- Delay automatically directing user, so that user can see the key has been successfully registered
- Consider scenario where key fails registration and how it affects UI

**Comment by newleeland** [comment]
@brynwhyman 
### The designs have been update Updated for WebAuthn in:
- [Setting up MFA for a user ](https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/325487128_CMS_-_Setup_-_Password_Setup)
- [Logging in for a user ](https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321188003_CMS_-_Login_-_Start)
- [User updating their MFA settings](https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321186220_CMS_-_Login_-_2FA_-_Editing_-_Reseting_-_User_Settings)

**Comment by robbieaverill** [comment]
@brynwhyman clarifying, is this ticket essentially "implement PUX designs for the webauthn authenticator"?

**Comment by Cheddam** [comment]
[Registration UI Overhaul](https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/24) is in PR.

Verify UI Overhaul still to come.

**Comment by brynwhyman** [comment]
> clarifying, is this ticket essentially "implement PUX designs for the webauthn authenticator"?

Yes, @robbieaverill

**Comment by NightJar** [comment]
Working on Verify UI overhaul.
