### ISSUE TITLE
Update YubiKey catalogue

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#15]
https://www.yubico.com/works-with-yubikey/catalog/silverstripe/

The YubiKey catalogue references OTP support, we should look at updating SilverStripe's information to also include reference to this module, assuming it becomes the recommendation for hardware tokens in MFA.

**Comment by ScopeyNZ** [comment]
Started contact but left your email address for them @brynwhyman 😉

**Comment by brynwhyman** [comment]
Our implementation for YubiKeys (for FIDO/ U2F and FIDO2) has been approved from both a technical and UX perspective 🎉 

The Solution Architect from Yubico has made some recommendations for changes in a future release, which I've raised/ commented on in: #70, #68, #57 

Next steps are to create some partnered marketing collateral and get the comms on their catalogue
