### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#16]
Tidy up bits that haven't been touched yet:

- [x] Better dev error logging
- [ ] Add more tests
- [x] Remove debug code
- [x] ~Investigate upgrading dependencies~

**Comment by robbieaverill** [comment]
Two outstanding A/Cs, moving back to ready

**Comment by brynwhyman** [comment]
> Investigate upgrading dependencies

I think this has since been captured here? https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/11#issuecomment-501055966

**Comment by robbieaverill** [comment]
Sure 👍
