### ISSUE TITLE
Provide domain/subdomain for PublicKeyCredentialRpEntity's "ID"?

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-webauthn-authenticator#18]
We have this:

```php
    protected function getRelyingPartyEntity(): PublicKeyCredentialRpEntity
    {
        return new PublicKeyCredentialRpEntity(
            (string) SiteConfig::current_site_config()->Title,
            /*Environment::getEnv('SS_BASE_URL') ?:*/ null,
            static::config()->get('application_logo')
        );
    }
```

The webauthn framework docs say this:

The ID can be null, the domain or sub-domain only of your application. The scheme, userinfo, port, path, user… are not allowed.

It could be www.sub.domain.com, sub.domain.com, domain.com but not com, www.sub.domain.com:1337, https://domain.com:443, sub.domain.com/index, https://user:password@www.domain.com.

Even if it is optional, we highly recommend to set the ID here. Some browsers (e.g. Mozilla Firefox) may refuse to handle the request considering it is unsecured.

---

We should use `Director::baseURL()` or similar to get the domain, I guess. This should factor in subsites support as well.

**Comment by brynwhyman** [comment]
Let's make sure this is tested with subsites!

**Comment by robbieaverill** [comment]
PR at #20

**Comment by robbieaverill** [comment]
Subsites sets an alternate base URL, which `Director::host()` factors in when making its decision.
