### ISSUE TITLE
WebAuthn backport to SS3: back and front end

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#19]
- just do it (after we do it)

**Comment by robbieaverill** [comment]
Just tested, I can't complete the registration process. I get a server error returned after I've pressed my key and press the "next" button.

**Comment by robbieaverill** [comment]
I think my problem was a missing Guzzle dependency, since I switched to @NightJar's branch with Git rather than Composer. Once the PSR-7 library is there it works nicely. Closing - follow ups can be made with @ScopeyNZ's work in the admin area.
