### ISSUE TITLE
[Demo issue] WebAuthn method cannot complete registration

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-webauthn-authenticator#48]
@newleeland commented on [Thu Jul 04 2019](https://github.com/silverstripe/silverstripe-mfa/issues/248)

During setup of security key on the demo, the key is verified but when clicking Complete registration button, button does nothing.

### How to reproduce
1. when setting up MFA, select security key method
2. Click Register Key, Tap key.
3. Key is verified, Click Complete registration

Browser: Chrome 75, Firefox 67

**Comment by robbieaverill** [comment]
@newleeland are you able to see what the errors are in your browser console/network tab when this happens? I'm unable to reproduce locally

**Comment by newleeland** [comment]
I can't replicate this problem anymore, as we account was deleted and recreated to see if it resolved the issue. After working with @Cheddam for a little while it appears its likely any issue with the CMS account rather than WebAuthn as garion's login worked on my computer.

**Comment by robbieaverill** [comment]
Cool, let's close for now and reopen if it pops up again
