### ISSUE TITLE
Unable to complete registration on Firefox

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-webauthn-authenticator#63]
Browser: Firefox 69.0.4

We're seeing some errors when users attempt to use a YubiKey on Firefox. When a user taps their YubiKey and clicks Complete Registration we're seeing this error in our logs:

```
The attestation statement format "packed" is not supported.
```

On the user's end they remain on the screen with the Complete button. User was able to register when they switched to Chrome.

## Notes

This issue is blocked by https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/73

**Comment by brynwhyman** [comment]
Hmm, weird. I couldn't recreate this on (OSX) Firefox version 69.0 (for a registration) or the latest version 70.0 (for a log in).

**Comment by brynwhyman** [comment]
I'll keep this open until we're able to test this on another operating system

**Comment by Cheddam** [comment]
This has been [resolved upstream](https://github.com/web-auth/webauthn-framework/issues/123), so we should be able to close this out by upgrading (we're currently on the 1.x line, current is 3.x.)

**Comment by brynwhyman** [comment]
Nice catch

**Comment by brynwhyman** [comment]
Marking this issue as blocked by: https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/73

**Comment by GuySartorelli** [comment]
#73 is resolved, which in turn resolves this issue. Closing.
