### ISSUE TITLE
Add a note in the docs that the `ext-gmp` library is required for the module

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#72]
This has been noted a few times by community members. Adding a note to the docs might just help for those who don't catch it on their local setup but could expect to need to make the change on their hosting platform.

**Comment by robbieaverill** [comment]
I've added it to the readme. Developers need to ensure they have an accurate development environment, otherwise there are many things (such as this) that may catch them out when deploying to a mysteriously different production environment.

**Comment by brynwhyman** [comment]
Thank you 😄

**Comment by dhensby** [comment]
Shouldn't this be in the composer dependencies, that way it's self enforcing...

**Comment by robbieaverill** [comment]
It is, this issue comes up when people install a project locally and deploy it to a server without GMP. I’ve expressed my opinion in the past that there is no bug here, but a short line in the readme doesn’t hurt!

**Comment by dhensby** [comment]
ah - right, indeed - there's not much we can do. We could add some line to the code with a simple `if !function_exists` and provide a helpful error too, but if people are deploying manually to environments they haven't even checked have the right software on, what can we do about that?

**Comment by michalkleiner** [comment]
> but if people are deploying manually to environments they haven't even checked have the right software on, what can we do about that?

Or... using a platform that offers package deployments that skip composer install while not providing enough public information allowing to truly recreate the env locally.

Could possibly be added to [CWP docs](https://www.cwp.govt.nz/developer-docs/en/2/working_with_projects/infrastructural_considerations/#php-extensions-2) and [SSP docs](https://docs.silverstripe.cloud/development/platform-yml-file/#php)? Search returned no results for of gmp, libgmp, ext-gmp.

**Comment by robbieaverill** [comment]
@michalkleiner AFAIK both CWP and SSP have the GMP package installed, so I don't see much point in documenting its requirement in those sets of docs

**Comment by michalkleiner** [comment]
@robbieaverill so is it then expected that developers for those platforms figure all development environment requirements and dependencies on the fly?

**Comment by robbieaverill** [comment]
@michalkleiner no, but if a common package is _not_ available on them then I would recommend documenting that
