### ISSUE TITLE
Upgrade to latest version of underlying library

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#73]
## Overview
One of the underlying libraries for this module has now seen two new major versions.

https://github.com/web-auth/webauthn-framework is up to v3 while this module is using v1.

Version 3.2 saw a fix to resolve browser compatibility issues. Currently, it appears registrations are not possible in at least Firefox and Microsoft Edge when running Windows OS. See #63

**Comment by GuySartorelli** [comment]
We're using v3 now. Closing this issue.
