### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-webauthn-authenticator#86]
**ACs:**
- Upgrade composer dependencies so that the WebAuthn MFA method can be composer installed on a local php environment without the use of the `--ignore-platform-reqs` flag
- Make any other code changes required for php8 support

It's likely that the following dependency will need to have a major version bump:

"web-auth/webauthn-lib": upgrade from ^1 to ^3.3
~~"web-auth/cose-lib": upgrade from ^1 to ^3.3~~
~~"web-auth/metadata-service": upgrade from ^1 to ^3.3~~

PRs:
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/97

**Comment by brynwhyman** [comment]
Not using the newest version of these dependencies has already uncovered issues with browser compatibility.

During post-upgrade testing please have a look at this issue too: https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/73

**Comment by ghost** [comment]
The Issue has now been open for 9 months, what is the status? Can we expect a solution soon?

**Comment by maxime-rainville** [comment]
Done. The fix will be available in the next release in January 2022
